Indian_Idol_prompt_file: /home/hardik/Final/Gemini_Inference/prompts_outputs/indian_idol_prompt.txt
Kapil_Sharma_prompt_file: /home/hardik/Final/Gemini_Inference/prompts_outputs/kapil_sharma_prompt1.txt
Singing_Superstars_prompt_file: /home/hardik/Final/Gemini_Inference/prompts_outputs/singing_superstars_prompt.txt
detection_threshold: 0.6
episode_id: bcuwyNifwbE
gemini_model: gemini-1.5-pro
gemini_temperature: 0
iou_threshold: 0.1
max_duration: 60
min_duration: 10
minimum_emotional_intensity: 3
minimum_laughter_intensity: 2
minimum_musical_intensity: 5
num_shorts: 4
overlap: 120
root_folder: /workspace/hardik/Final/outputs
segment_length: 420
series: Singing_Superstars
temperature: 0.0
vinet_model_path: /home/hardik/Final/ViNet_Saliency/saved_models/ViNet_DHF1K.pt
workers_ViNet: 20
workers_gemini: 15
